# src/spfetch/auth.py
import msal
import logging
import webbrowser  # <- Nova biblioteca nativa adicionada / New native library added
from abc import ABC, abstractmethod
from .exceptions import AuthenticationError

logger = logging.getLogger("spfetch")


class SharePointAuth(ABC):
    """
    Classe base abstrata para métodos de autenticação.
    Abstract base class for authentication methods.
    """

    @abstractmethod
    def get_token(self) -> str:
        pass


class DeviceCodeAuth(SharePointAuth):
    """
    Autenticação interativa via Device Code (Suporta MFA).
    Interactive authentication via Device Code (Supports MFA).
    """

    def __init__(self, tenant_id: str, client_id: str, scopes: list = None):
        self.tenant_id = tenant_id
        self.client_id = client_id
        self.scopes = scopes or ["https://graph.microsoft.com/Sites.Read.All"]
        self.authority = f"https://login.microsoftonline.com/{tenant_id}"
        self.app = msal.PublicClientApplication(
            self.client_id, authority=self.authority
        )
        self._cached_token = None

    def get_token(self) -> str:
        if self._cached_token:
            return self._cached_token

        logger.info("Iniciando fluxo de autenticação via Device Code...")
        logger.info("Starting Device Code authentication flow...")

        flow = self.app.initiate_device_flow(scopes=self.scopes)
        if "user_code" not in flow:
            logger.error("Falha ao criar o fluxo de dispositivo.")
            logger.error("Failed to create device flow.")
            raise AuthenticationError(
                "Falha ao criar o fluxo de dispositivo. / Failed to create device flow."
            )

        # Extraímos o link e o código gerados pela Microsoft
        # We extract the link and code generated by Microsoft
        url_login = flow.get("verification_uri", "https://microsoft.com/devicelogin")
        codigo_usuario = flow.get("user_code")

        print(f"\n[AÇÃO NECESSÁRIA / ACTION REQUIRED]: {flow['message']}")
        print(f"======================================================")
        print(f"👉 CÓDIGO / CODE: {codigo_usuario}")
        print(f"======================================================\n")

        # Tenta abrir o navegador automaticamente
        # Attempts to open the browser automatically
        try:
            logger.info("Abrindo o navegador padrão automaticamente...")
            logger.info("Opening the default browser automatically...")
            webbrowser.open(url_login)
        except Exception as e:
            logger.debug(f"Não foi possível abrir o navegador: {e}")
            logger.debug(f"Could not open the browser: {e}")

        # Aguarda a aprovação do usuário no navegador
        # Waits for the user's approval in the browser
        result = self.app.acquire_token_by_device_flow(flow)

        if "access_token" in result:
            logger.info("Autenticação concluída com sucesso!")
            logger.info("Authentication completed successfully!")
            self._cached_token = result["access_token"]
            return self._cached_token

        error_msg = result.get("error_description", "Erro desconhecido / Unknown error")
        logger.error(f"Erro de Autenticação: {error_msg}")
        raise AuthenticationError(error_msg)


class ClientSecretAuth(SharePointAuth):
    """
    Autenticação silenciosa via Client Secret (Service Principal).
    Silent authentication via Client Secret (Service Principal).
    """

    def __init__(
        self, tenant_id: str, client_id: str, client_secret: str, scopes: list = None
    ):
        self.tenant_id = tenant_id
        self.client_id = client_id
        self.client_secret = client_secret
        self.scopes = scopes or ["https://graph.microsoft.com/.default"]
        self.authority = f"https://login.microsoftonline.com/{tenant_id}"
        self.app = msal.ConfidentialClientApplication(
            self.client_id,
            authority=self.authority,
            client_credential=self.client_secret,
        )
        self._cached_token = None

    def get_token(self) -> str:
        if self._cached_token:
            return self._cached_token

        logger.debug("Obtendo token via Client Secret...")
        result = self.app.acquire_token_for_client(scopes=self.scopes)

        if "access_token" in result:
            logger.debug("Token obtido com sucesso!")
            self._cached_token = result["access_token"]
            return self._cached_token

        error_msg = result.get("error_description", "Erro desconhecido / Unknown error")
        logger.error(f"Erro de Autenticação (Client Secret): {error_msg}")
        raise AuthenticationError(error_msg)
