name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Linting Tools
        run: pip install black ruff
      - name: Check code style
        run: |
          black --check .
          ruff check .

  tests:
    needs: quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # Agiliza o processo
      - name: Install dependencies
        run: |
          pip install .[test,azure,pandas,s3,gcs]
          # Usamos o seu Makefile para garantir consistência
          make install-all
          pip install pytest pytest-asyncio
      - name: Run Async Tests
        run: |
          make test